name: Image test routine

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'

jobs:
  test-suite:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"
    - name: Install and test docker
      run: |
        # set -x
        brew install docker docker-compose colima
        colima start
        docker version
        mkdir -p ~/.docker/cli-plugins
        ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
        docker compose version
        docker-compose version
        cat /etc/docker/daemon.json || true
        cat /Users/runner/.docker/daemon.json || true
        docker buildx version || true
        docker buildx ls || true
        docker run --rm hello-world
    - name: Pull all images
      run: |
        docker compose pull --ignore-pull-failures
    - name: Install test harness
      run: |
        yarn add leia-parser mocha chai@4 command-line-test
    - name: Generate test files
      run: |
        yarn leia "TESTING*.md" test -r 2 -s 'Start up tests' -t 'Verification commands' -c 'Destroy tests' --split-file
    - name: Run docker-compose tests
      run: |
        yarn mocha --timeout 900000 test/*compose*.func.js
